### ISSUE TITLE
Threshold issue

### ISSUE THREAD

**Issue by SaulShen** [XC-Zhang/zxc.tgbot.ingress-farming#6]
When use a threshold more than 9, it can't work. 
A test poll uses these  options:
```
>20 test1
>-20 test2
> 20 test3
>- 20 test4
> - 20 test5
```
The result is : [https://photos.app.goo.gl/YGNXmHW7zDMkQoLRA](url).
May "\d" should turn to "\d+" ? 

阈值大于9时，该功能未生效。
测试例子如上。
看了下JS的正则，代码中"\d"似乎需要改为"\d+"？

**Comment by XC-Zhang** [comment]
Confirmed! Thanks for report! 😃 
Schedule to repair tomorrow.
